[package]
name = "stpc_logging"
version = "0.1.0-alpha.0"
edition = "2024"
authors = ["Konstantin Gorshkov"]
license = "GPL-3.0-or-later"

[dependencies]
stpc_core = { path = "../stpc_core" }
chrono = "0.4"
lazy_static = "1.4"
colored = "2.0"