[package]
name = "stpc_time"
version = "0.1.0-alpha.0"
edition = "2024"
authors = ["Konstantin Gorshkov"]
license = "GPL-3.0-or-later"

[dependencies]
ntp = "0.5.0"
stpc_core = { path = "../stpc_core" }
